development:
  host: 199.204.217.189
  username: albers
  password: up1d9A0Xl0dE5me
  database: albers_development

test:
  host: localhost
  database: albers_test

# set these environment variables on your prod server
production:
  host: 199.204.217.189
  port: <%= ENV['MONGOID_PORT'] %>
  username: "albers"
  password: "KJfzqXccVMU44Vv"
  database: "albers"
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
