production:
  solr:
    hostname: 199.204.217.189
    path: '/solr'
    port: 8080
    log_level: WARNING

development:
  solr:
    hostname: 199.204.217.189
    path: '/solr-devel'
    port: 8080
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
